### ISSUE TITLE
Invalid scapy library version?

### ISSUE THREAD

**Issue by Janek79ax** [domienschepers/wifi-framework#3]
Hey, 
It looks like it fails with:

(venv) ubuntu@ubuntu:~/wifi-framework$ ./hostap.py wlan0 --ap
/home/ubuntu/wifi-framework/dependencies/libwifi/wifi.py:96: SyntaxWarning: invalid escape sequence '\d'
  p = re.compile("channel (\d+)")
/home/ubuntu/wifi-framework/dependencies/libwifi/wifi.py:125: SyntaxWarning: invalid escape sequence '\w'
  p = re.compile("type (\w+)")
Traceback (most recent call last):
  File "/home/ubuntu/wifi-framework/./hostap.py", line 5, in <module>
    from dependencies.libwifi.wifi import log, STATUS, change_log_level
  File "/home/ubuntu/wifi-framework/dependencies/libwifi/__init__.py", line 1, in <module>
    from .wifi import *
  File "/home/ubuntu/wifi-framework/dependencies/libwifi/wifi.py", line 5, in <module>
    from scapy.all import *
  File "/home/ubuntu/wifi-framework/setup/venv/lib/python3.12/site-packages/scapy/all.py", line 10, in <module>
    from scapy.base_classes import *
  File "/home/ubuntu/wifi-framework/setup/venv/lib/python3.12/site-packages/scapy/base_classes.py", line 32, in <module>
    from scapy.modules.six.moves import range
ModuleNotFoundError: No module named 'scapy.modules.six.moves'

Any hints re actual environment used, python version, scapy version etc?
Thanks!

**Comment by vanhoefm** [comment]
Having seen this error in other projects: this error message can likely be solved by installing a newer scapy version (or using an older version of Python).
